### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by almndbtr** [soundxyz/protocol-public#13]
👋  Hello, soundxyz!

I'm wondering if you all have plans to introduce [contributing guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) to this repository?

I'm interested in contributing (and perhaps others are too 😉), but I'm not quite sure where the best place to start. From the last 48 hours, I see there's healthy activity from the team and I'd love to lend a hand!

However, I want to make sure the time that I spend on opening issues and PRs are worthwhile (and welcome!), so it would be lovely to get some direction from the team on where you all welcome the most help (good first issues, feature implementation, bug fixes, etc.).

Thank you for considering my ask! 🙇‍♂️

**Comment by gigamesh** [comment]
Hey @almndbtr - good question! 

At the moment this repo is primarily intended to be read-only, although we plan to open it up to contributions as time goes on. We definitely welcome bug or vulnerability reports (although those are best sent privately). 

I'm going to update the readme with some info to make it clear though. thanks for the interest!

**Comment by almndbtr** [comment]
Thanks @gigamesh ! I'll leave this open until the README is updated. Including an email address or form to submit bugs/vulnerabilities would be really great, too. 🙏🏾

**Comment by almndbtr** [comment]
@gigamesh - Thank you for your [Minimal viable readme](https://github.com/soundxyz/protocol-public/commit/a2408a4ba5c9bc33a58e06f953842b3e64868002). ✨

This is resolved. Closing! ✌️
